{{- range $job := .Values.jobs }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ $job.name }}
  namespace: {{ .Release.Namespace }}
  {{- if $job.annotations }}
  annotations:
    {{- toYaml $job.annotations | nindent 4 }}
  {{- end }}
spec:
  template:
    spec:
      {{- if $job.imagePullSecrets }}
      imagePullSecrets:
      - name: {{ $job.imagePullSecrets }}
      {{- end }}
      containers:
      - image: "{{ $job.image.url }}"
        imagePullPolicy: {{ $job.image.imagePullPolicy }}
        name: {{ $job.name }}
        {{- if $job.env }}
        env:
        {{- include "common.tplvalues.render" (dict "value" $job.env "context" $) | nindent 8 }}
        {{- end }}
        {{- if $job.envFrom }}
        envFrom:
        {{- include "common.tplvalues.render" (dict "value" $job.envFrom "context" $) | nindent 8 }}
        {{- end }}
        {{- if $job.command }}
        command: {{ toYaml $job.command | nindent 8 }}
        {{- end }}
        {{- if $job.resources }}
        resources:
          {{ toYaml $job.resources | nindent 10 }}
        {{- end }}
      {{- if $job.nodeSelector }}
      nodeSelector:
        {{ toYaml $job.nodeSelector | nindent 8 }}
      {{- end }}
      {{- if $job.affinity }}
      affinity:
        {{ toYaml $job.affinity | nindent 8 }}
      {{- end }}
      {{- if $job.tolerations }}
      tolerations:
        {{ toYaml $job.tolerations | nindent 8 }}
      {{- end }}
      restartPolicy: {{ $job.restartPolicy }}
  backoffLimit: {{ $job.backoffLimit }}
{{- end }}
